spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            # my-docent 연결용 정보
            client-id: ???
            client-secret: ???
            redirect-uri: ??? # 코드받는 엔드 포인트
            client-authentication-method: ??? # http method
            authorization-grant-type: ??? # 인증 방식
            scope:
              - profile_nickname
            client-name: kakao
        provider:
          kakao:
            authorization-uri: ??? # 로그인 페이지
            token_uri: ??? # 토근 api
            user-info-uri: ??? # 사용자 정보 조회 api
            user-name-attribute: ???
jwt:
  secret: ???
---
spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      client:
        registration:
          kakao:
            # my-docent 연결용 정보
            client-id: ???
            client-secret: ???
            redirect-uri: ??? # 코드받는 엔드 포인트
            client-authentication-method: ??? # http method
            authorization-grant-type: ??? # 인증 방식
            scope:
              - profile_nickname
            client-name: kakao
        provider:
          kakao:
            authorization-uri: ??? # 로그인 페이지
            token_uri: ??? # 토근 api
            user-info-uri: ??? # 사용자 정보 조회 api
            user-name-attribute: id
jwt:
  secret: ???