spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
hibernate:
  ddl-auto: none
properties:
  hibernate:
    show_sql: true
    format_sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
hibernate:
  ddl-auto: none
properties:
  hibernate:
    show_sql: true
    format_sql: true